### ISSUE TITLE
Improvement or Suggestion

### ISSUE THREAD

**Issue by EviLMang0** [thenurhabib/vulscanpro#2]
Please add some extra features like subdomain enumeration, directory brute-forcing, fetching URLs with parameters from the Wayback machine, and sorting them in patterns (gf-patterns). Then scanning those patterns with tools accordingly.
Make something like this bro.

**Comment by thenurhabib** [comment]
thanks for your suggestions. I'll at this on my next release.

**Comment by thenurhabib** [comment]
add*
